# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 7) do

  create_table "comments", :force => true do |t|
    t.column "game_id",    :integer,  :null => false
    t.column "author_id",  :integer,  :null => false
    t.column "created_at", :datetime, :null => false
    t.column "comment",    :text,     :null => false
  end

  create_table "games", :force => true do |t|
    t.column "owner_id",    :integer,  :null => false
    t.column "description", :text
    t.column "sgf",         :text,     :null => false
    t.column "uploaded_at", :datetime, :null => false
  end

  create_table "players", :force => true do |t|
    t.column "name",         :string,                      :null => false
    t.column "surname",      :string,                      :null => false
    t.column "email",        :string,                      :null => false
    t.column "rank",         :string,                      :null => false
    t.column "created_at",   :datetime,                    :null => false
    t.column "secret_code",  :string,                      :null => false
    t.column "is_confirmed", :boolean,  :default => false, :null => false
    t.column "is_removed",   :boolean,  :default => false, :null => false
  end

  create_table "ranks", :force => true do |t|
    t.column "value",    :string,  :null => false
    t.column "order_id", :integer, :null => false
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                  :string,                  :null => false
    t.column "password",               :string,                  :null => false
    t.column "email",                  :string,                  :null => false
    t.column "number_of_logins",       :integer,  :default => 0, :null => false
    t.column "last_login_at",          :datetime
    t.column "created_at",             :datetime,                :null => false
    t.column "remember_token",         :text
    t.column "remember_token_expires", :datetime
  end

  add_index "users", ["remember_token"], :name => "index_users_on_remember_token", :unique => true

end
