development:
  adapter: postgresql
  database: baduk_development
  username: postgres 
  password: postgres
  host: localhost
  port: 5432
  encoding: UTF8

test:
  adapter: postgresql
  database: baduk_test
  username: postgres 
  password: postgres
  host: localhost
  port: 5432
  encoding: UTF8

production:
  adapter: postgresql
  database: baduk.pl
  username: baduk.pl
  password: foo 
  host: localhost
  port: 5432
  encoding: UTF8
